//
// CFormatter.hpp --- C/C++ header input and output.
//
// Copyright (c) 2013 Paul Ward <asmodai@gmail.com>
//
// Time-stamp: <Thursday May 30, 2013 00:58:12 asmodai>
// Revision:   73
//
// Author:     Paul Ward <asmodai@gmail.com>
// Maintainer: Paul Ward <asmodai@gmail.com>
// Created:    29 May 2013 04:19:38
// Keywords:   
// URL:        not distributed yet
//
// {{{ License:
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 3
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>.
//
// }}}
// {{{ Commentary:

              // }}}

#ifndef _CFormatter_hpp_
#define _CFormatter_hpp_

/**
 * @file CFormatter.hpp
 * @author Paul Ward
 * @brief Outputs version information to C/C++ header files.
 */

#include "Formatter.hpp"

#define DRE                                     \
  "(?:VERSION[_])(\\w+)(?:\\s+)(\\d+)"

#define SRE                                             \
  "(?:[{]\\s*)(\\d+)(?:[,]\\s+)(\\d+)(?:[,]\\s+)(\\d+)" \
  "(?:[,]\\s+)(\\d+)(?:[,]\\s+)(\\d+)(?:\\s*[}])"

class CFormatter
  : public Formatter
{
  FORMATTER_PREAMBLE(CFormatter, "C/C++")

  
public:
  
  bool read(QTextStream &stream,
            VersionInfo &info)
  {
    QString buffer = stream.readAll();
    bool    found  = false;
    
    if (buffer.isNull() || buffer.length() > 0) {
      /*
       * Start by preparing the buffer.
       */
      buffer.replace(QRegExp("\\s*\n\\s*"), " ");
      buffer.replace(QRegExp("="), " = ");
      buffer = buffer.simplified();
    
      /*
       * First, attempt to find the data using the regular expression
       * that matches the C/C++ structure definition.
       */
      {
        QRegExp re(SRE);
        int     cnt = 0;
        int     pos = 0;
        
        while ((pos = re.indexIn(buffer, pos)) != -1)
        {  
          ++cnt;
          pos += re.matchedLength();
          
          info.setBaseYear(re.cap(1).toInt());
          info.setMajor(re.cap(2).toInt());
          info.setMinor(re.cap(3).toInt());
          info.setPatch(re.cap(4).toInt());
          info.setBuild(re.cap(5).toInt());
          
          found = true;
        }
      }
      
      /*
       * If we didn't locate the version information via the above
       * regular expression, then try looking for a heap of `#define'
       * statements instead.
       */
      if (!found) {
        QRegExp re(DRE);
        int     cnt = 0;
        int     pos = 0;
        
        while ((pos = re.indexIn(buffer, pos)) != -1)
        {
          ++cnt;
          pos += re.matchedLength();
          
          if (re.cap(1).contains("BASE_YEAR")) {
            info.setBaseYear(re.cap(2).toInt());
          } else if (re.cap(1).contains("MAJOR")) {
            info.setMajor(re.cap(2).toInt());
          } else if (re.cap(1).contains("MINOR")) {
            info.setMinor(re.cap(2).toInt());
          } else if (re.cap(1).contains("PATCH")) {
            info.setPatch(re.cap(2).toInt());
          } else if (re.cap(1).contains("BUILD")) {
            info.setBuild(re.cap(2).toInt());
          }
        }
        
        found = true;
      }
      
      return found;
    }
    
    return false;
  }                             // bool read(...)
  
  bool write(QTextStream &stream,
             VersionInfo  info)
  {
    stream << "/* ----------------------------------------------------" << endl
           << " * Automatically generated by VerBuild "
           << VERSION_STRING << "."                                     << endl
           << " * Do not edit by hand."                                 << endl
           << " * ----------------------------------------------------" << endl
           << " */"                                                     << endl
           << endl
           << "#ifndef __VersionInfo_Header__"                          << endl
           << "#define __VersionInfo_Header__"                          << endl
           << endl;
    
    if (m_flags & Formatter::Doxygen) {
      stream << "/**"                                                   << endl
             << " * @file " << m_fileName                               << endl
             << " * @author VarBuild " << VERSION_STRING                << endl
             << " * @brief Provides version information."               << endl
             << " */"                                                   << endl
             << endl;
    }
    
    if (m_flags & Formatter::Basic) {
      if (m_flags & Formatter::Doxygen) {
        stream << "/**"                                                 << endl
               << " * @def VERSION_MAJOR"                               << endl
               << " * @brief Major version number."                     << endl
               << " *"                                                  << endl
               << " * @def VERSION_MINOR"                               << endl
               << " * @brief Minor version number."                     << endl
               << " *"                                                  << endl
               << " * @def VERSION_PATCH"                               << endl
               << " * @brief Patch number."                             << endl
               << " *"                                                  << endl
               << " * @def VERSION_BUILD"                               << endl
               << " * @brief Build number."                             << endl
               << " *"                                                  << endl
               << " * @def VERSION_BASE_YEAR"                           << endl
               << " * @brief The year the project was started."         << endl
               << " *"                                                  << endl
               << " * @def VERSION_DATE"                                << endl
               << " * @brief The date this build was compiled."         << endl
               << " *"                                                  << endl
               << " * @def VERSION_TIME"                                << endl
               << " * @brief The time this build was compiled."         << endl
               << " *"                                                  << endl
               << " * @def VERSION_STRING"                              << endl
               << " * @brief String representation of the version."     << endl
               << " */"
               << endl;
      }
      
      stream << "#define VERSION_MAJOR      " << info.major()           << endl
             << "#define VERSION_MINOR      " << info.minor()           << endl
             << "#define VERSION_PATCH      " << info.patch()           << endl
             << "#define VERSION_BUILD      " << info.build()           << endl
             << endl
             << "#define VERSION_BASE_YEAR  " << info.baseYear()        << endl
             << "#define VERSION_DATE       "
                << "\"" << info.buildDate().toString() << "\""          << endl
             << "#define VERSION_TIME       "
                << "\"" << QTime::currentTime().toString() << "\""      << endl
             << "#define VERSION_STRING     "
                << "\"" << info.toString() << "\""                      << endl
             << endl;
    }
    
    if (m_flags & Formatter::Struct) {
      if (m_flags & Formatter::Doxygen) {
        stream << "/**"                                                 << endl
               << " * @brief Version number structure."                 << endl
               << " *"                                                  << endl
               << " * @var baseYear"                                    << endl
               << " * @brief The year the project was started."         << endl
               << " *"                                                  << endl
               << " * @var major"                                       << endl
               << " * @brief Major version number"                      << endl
               << " *"                                                  << endl
               << " * @var minor"                                       << endl
               << " * @brief Minor version number."                     << endl
               << " *"                                                  << endl
               << " * @var patch"                                       << endl
               << " * @brief Patch number."                             << endl
               << " *"                                                  << endl
               << " * @var build"                                       << endl
               << " * @brief Build number."                             << endl
               << " */"
               << endl;
      }
          
      stream << "static struct VersionNumber_s {"                       << endl
             << "  int baseYear;"                                       << endl
             << "  int major;"                                          << endl
             << "  int minor;"                                          << endl
             << "  int patch;"                                          << endl
             << "  int build;"                                          << endl
             << "} VersionNumber = {"                                   << endl
             << "  " << info.baseYear() << ","                          << endl
             << "  " << info.major() << ","                             << endl
             << "  " << info.minor() << ","                             << endl
             << "  " << info.patch() << ","                             << endl
             << "  " << info.build()                                    << endl
             << "};"                                                    << endl
             << endl;
    }
      
    stream << "#endif // !__VersionInfo_Header__"
           << endl;
    
    return true;
  }                             // write(...)
  
};                              // class COutput

FORMATTER_REGISTER(CFormatter, "C")

#endif // !_CFormatter_hpp_

// CFormatter.hpp ends here
