/* ------------------------------------
 * Automatically generated by VerBuild.
 * Do not edit by hand.
 * ------------------------------------
 */

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

/**
 * @file version.hpp
 * @author VarBuild 0.1.0.529
 * @brief Provides version information.
 */

/**
 * @def VERSION_MAJOR
 * @brief Major version number.
 *
 * @def VERSION_MINOR
 * @brief Minor version number.
 *
 * @def VERSION_PATCH
 * @brief Patch number.
 *
 * @def VERSION_BUILD
 * @brief Build number.
 *
 * @def VERSION_BASE_YEAR
 * @brief The year the project was started.
 *
 * @def VERSION_DATE
 * @brief The date this build was compiled.
 *
 * @def VERSION_TIME
 * @brief The time this build was compiled.
 *
 * @def VERSION_STRING
 * @brief String representation of the version.
 */
#define VERSION_MAJOR      0
#define VERSION_MINOR      1
#define VERSION_BUILD      529
#define VERSION_PATCH      0

#define VERSION_BASE_YEAR  2013
#define VERSION_DATE       "Wed May 29 2013"
#define VERSION_TIME       "05:04:10"
#define VERSION_STRING     "0.1.0.529"

#endif // !__VersionInfo_Header__
