/* ----------------------------------------------------
 * Automatically generated by VerBuild 1.0.601.1.
 * Do not edit by hand.
 * ----------------------------------------------------
 */

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

/**
 * @file version.hpp
 * @author VarBuild 1.0.601.1
 * @brief Provides version information.
 */

/**
 * @def VERSION_MAJOR
 * @brief Major version number.
 *
 * @def VERSION_MINOR
 * @brief Minor version number.
 *
 * @def VERSION_BUILD
 * @brief Build number.
 *
 * @def VERSION_PATCH
 * @brief Patch number.
 *
 * @def VERSION_BASE_YEAR
 * @brief The year the project was started.
 *
 * @def VERSION_DATE
 * @brief The date this build was compiled.
 *
 * @def VERSION_TIME
 * @brief The time this build was compiled.
 *
 * @def VERSION_STRING
 * @brief String representation of the version.
 */
#define VERSION_MAJOR      1
#define VERSION_MINOR      0
#define VERSION_BUILD      601
#define VERSION_PATCH      1

#define VERSION_BASE_YEAR  2013
#define VERSION_DATE       "Sat Jun 1 2013"
#define VERSION_TIME       "10:32:31"
#define VERSION_STRING     "1.0.601.1"

/**
 * @brief Version number structure.
 *
 * @var baseYear
 * @brief The year the project was started.
 *
 * @var major
 * @brief Major version number
 *
 * @var minor
 * @brief Minor version number.
 *
 * @var patch
 * @brief Patch number.
 *
 * @var build
 * @brief Build number.
 */
static struct VersionNumber_s {
  int baseYear;
  int major;
  int minor;
  int build;
  int patch;
} VersionNumber = {
  2013,
  1,
  0,
  601,
  1
};

#endif // !__VersionInfo_Header__
