/*
 * ----------------------------------------------------
 * Automatically generated by VerBuild 2.0.613.0.
 * Do not edit by hand.
 * ----------------------------------------------------
 */

#pragma once

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

#define VERSION_MAJOR      2
#define VERSION_MINOR      1
#define VERSION_BUILD      615
#define VERSION_PATCH      0

#define VERSION_BASE_YEAR  2013
#define VERSION_DATE       "2020-Jul-04"
#define VERSION_TIME       "15:11:21"
#define VERSION_STRING     "2.1.615.0"

#endif // !__VersionInfo_Header__
