/*
 * ----------------------------------------------------
 * Automatically generated by VerBuild 2.0.602.0.
 * Do not edit by hand.
 * ----------------------------------------------------
 */

#pragma once

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

#define VERSION_MAJOR      2
#define VERSION_MINOR      0
#define VERSION_BUILD      603
#define VERSION_PATCH      0

#define VERSION_BASE_YEAR  2017
#define VERSION_DATE       "2017-Nov-26"
#define VERSION_TIME       "01:40:26"
#define VERSION_STRING     "2.0.603.0"

#endif // !__VersionInfo_Header__
