/*
 * ----------------------------------------------------
 * Automatically generated by VerBuild 2.0.625.0.
 * Do not edit by hand.
 * ----------------------------------------------------
 */

#pragma once

#ifndef __VersionInfo_Header__
#define __VersionInfo_Header__

#define VERSION_MAJOR      2
#define VERSION_MINOR      0
#define VERSION_BUILD      609
#define VERSION_PATCH      0

#define VERSION_BASE_YEAR  2013
#define VERSION_DATE       "2020-Jun-30"
#define VERSION_TIME       "10:24:44"
#define VERSION_STRING     "2.0.609.0"

#endif // !__VersionInfo_Header__
