#!/bin/bash
# -*- Mode: Shell-script -*-
#
# dog-food --- Dog food :)
#
# Copyright (c) 2020 Paul Ward <asmodai@gmail.com>
#
# Author:     Paul Ward <asmodai@gmail.com>
# Maintainer: Paul Ward <asmodai@gmail.com>
# Created:    30 Jun 2020 11:40:44
#
# {{{ License:
#
# This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY  WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# }}}
# {{{ Commentary:
#
# }}}

if [ $# -ne 3 ];
then
    echo "No arguments provided"
    exit 1
fi

if [ ! -x $1 ];
then
    echo "Cannot execute ${1}"
    exit 0
fi

if [ x"${2}" == x"Debug" ];
then
    echo "Ignoring DEBUG mode"
    exit 0
fi

$1 -c           \
   -f '*.*.+.*' \
   -i simple    \
   -t c         \
   -g basic     \
   -y 2013      \
   -o $3

# dog-food ends here.
