#!/bin/bash
# -*- Mode: Shell-script -*-
#
# install-hooks --- Install git hooks.
#
# Copyright (c) 2017 Paul Ward <asmodai@gmail.com>
#
# Author:     Paul Ward <asmodai@gmail.com>
# Maintainer: Paul Ward <asmodai@gmail.com>
# Created:    25 Nov 2017 04:38:48
#
# {{{ License:
#
# This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY  WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# }}}
# {{{ Commentary:
#
# }}}

_scriptpath="$(cd "$(dirname "$0")" ; pwd -P)"

echo "Copying git hooks: "
cp -v ${_scriptpath}/../git-hooks/* ${_scriptpath}/../.git/hooks/

# Let's play it safe.
chmod 755 ${_scriptpath}/../.git/hooks/*

# install-hooks ends here.
